# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "jekyll"

# If you want to use GitHub Pages, remove the "gem "jekyll"" above and
# uncomment in the line below. To upgrade, run 'bundle update guthub-pages'.

gem "github-pages", group: :jekyll_plugins